import Head from "next/head";

import { api } from "~/utils/api";
import GraphViz from "./components/graph";

export default function Home() {
  const nodes = api.graph.nodes.useQuery();
  const edges = api.graph.edges.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <GraphViz nodes={nodes.data} edges={edges.data} />
      </main>
    </>
  );
}
